name: utp_in_me
description: An Universiti Teknologi PETRONAS application

publish_to: 'none'

version: 24.01.121330

environment:
  sdk: '>=3.1.0 <3.16.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  flutter_adaptive_scaffold: ^0.1.6
  gridview_menu: ^1.0.6
  webview_flutter: ^4.0.2
  flutter_launcher_icons: ^0.13.1
  google_maps_flutter: ^2.4.0
  qr_flutter: ^4.1.0
  google_fonts: ^4.0.4
  material_color_utilities: ^0.5.0
  #location: ^4.4.0
  flutter_svg: ^2.0.0+1
  #permission_handler: ^10.2.0
  dynamic_color: ^1.5.4
  quick_actions: ^1.0.1
  #adaptive_navigation: ^0.0.9
  #latlong2: ^0.8.1
  qr_code_scanner: ^1.0.1
  xml2json: ^6.0.0
  http: ^1.1.0
  url_launcher: ^6.1.14
  cached_network_image: ^3.2.0
  #flutter_html: ^2.2.1
  #webfeed_revised: ^0.7.0
  flutter_image_slideshow: ^0.1.6
  firebase_core: ^2.15.1
  firebase_auth: ^4.9.0
  syncfusion_flutter_datagrid: ^23.2.6
  syncfusion_flutter_calendar: ^23.2.6
  awesome_ripple_animation: ^1.0.2
  animations: ^2.0.8
  loading_animation_widget: ^1.2.0+4
  flutter_custom_tabs: ^1.2.1
  geolocator: ^10.0.1
  package_info_plus: ^4.1.0
  salomon_bottom_bar: ^3.3.2
  #eva_icons_flutter: ^3.1.0
  microsoft_graph_api: ^0.0.6
  aad_oauth: ^1.0.0
  flutter_speed_dial: ^7.0.0
  dash_chat_2: ^0.0.19
  flutter_gemini: ^2.0.1
  flutter_markdown: ^0.6.18+3
  

 
 
 
  


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
  - assets/profile_pic.png
  - assets/chan.jpg
  - assets/UTP-logo.png
  - assets/utp-single-logo.png
  - assets/ch.jpg
  - assets/app_logo.png
  - assets/carousel_pic/ulife_live.png
  - assets/carousel_pic/1.jpg
  - assets/carousel_pic/2.png
  - assets/prototype/1.jpg
  - assets/prototype/2.jpg
  - assets/prototype/3.jpg
  - assets/prototype/4.jpg
  - assets/prototype/5.jpg
  - assets/prototype/6.png
  - assets/prototype/7.jpg
  - assets/prototype/news_1.jpg

  fonts:
      - family: GoogleSans
        fonts:
          - asset: assets/fonts/google_sans_regular.ttf
          - asset: assets/fonts/google_sans_italic.ttf
            style: italic
      - family: Kaleko
        fonts:
          - asset: assets/fonts/kaleko_regular.ttf
 
